name: Promote MLflow Model

on:
  workflow_dispatch:  # enables manual trigger from GitHub UI

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow

      - name: Run promotion script
        run: python mlops/evaluate_and_promote.py
